### ISSUE TITLE
Ant: com.jcraft.jsch.JSchException: reject HostKey 

### ISSUE THREAD

**Issue by charlesdccti** [charlesdccti/Apache-Ant-Trainning#1]
[charles:...a-projetos-Java-capitulo2 2]$ ant deploy-remoto                                                                                                                                 (master✱) 
Buildfile: /Users/charles/Downloads/Curso-Ant-Build-robusto-para-projetos-Java-capitulo2 2/build.xml

limpar:
   [delete] Deleting directory /Users/charles/Downloads/Curso-Ant-Build-robusto-para-projetos-Java-capitulo2 2/BUILD

init:
    [mkdir] Created dir: /Users/charles/Downloads/Curso-Ant-Build-robusto-para-projetos-Java-capitulo2 2/BUILD
    [mkdir] Created dir: /Users/charles/Downloads/Curso-Ant-Build-robusto-para-projetos-Java-capitulo2 2/BUILD/CLASSES
    [mkdir] Created dir: /Users/charles/Downloads/Curso-Ant-Build-robusto-para-projetos-Java-capitulo2 2/BUILD/CLASSES-TESTE

copiar-recursos:
     [copy] Copying 1 file to /Users/charles/Downloads/Curso-Ant-Build-robusto-para-projetos-Java-capitulo2 2/BUILD/CLASSES

compilar:
    [javac] /Users/charles/Downloads/Curso-Ant-Build-robusto-para-projetos-Java-capitulo2 2/build.xml:52: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 5 source files to /Users/charles/Downloads/Curso-Ant-Build-robusto-para-projetos-Java-capitulo2 2/BUILD/CLASSES

empacotar:
      [war] Building war: /Users/charles/Downloads/Curso-Ant-Build-robusto-para-projetos-Java-capitulo2 2/BUILD/agenda.war

deploy-remoto:
      [scp] Connecting to ec2-3-85-119-47.compute-1.amazonaws.com:22

BUILD FAILED
/Users/charles/Downloads/Curso-Ant-Build-robusto-para-projetos-Java-capitulo2 2/build.xml:98: com.jcraft.jsch.JSchException: reject HostKey: ec2-3-85-119-47.compute-1.amazonaws.com
	at com.jcraft.jsch.Session.checkHost(Session.java:799)
	at com.jcraft.jsch.Session.connect(Session.java:345)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at org.apache.tools.ant.taskdefs.optional.ssh.SSHBase.openSession(SSHBase.java:279)
	at org.apache.tools.ant.taskdefs.optional.ssh.Scp.upload(Scp.java:386)
	at org.apache.tools.ant.taskdefs.optional.ssh.Scp.execute(Scp.java:277)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
	at org.apache.tools.ant.Main.runBuild(Main.java:830)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)

**Comment by charlesdccti** [comment]
> **The solution is to add trust="true" to the scp task:**

```
<scp file="${dist.dir}/${war.file}" 
     todir="${deploy.username}:${deploy.password}@${deploy.server}:${deploy.dir}" 
     trust="true"/>
```

Referência: https://www.xinotes.net/notes/note/894/
